### ISSUE TITLE
Some additional information is required to get this to post 100%

### ISSUE THREAD

**Issue by SteveMyers75** [smealum/iosuhax#1]
Almost there, but need a little assistance getting it to process 0x8140000 +
  It looks like some of the binaries were manually created
[**Edit: Got through the above issue by creating them manually.**]

**Last thing (we think)**
It looks like the last thing we need is to understand how the crypto applies the keys

OK, this can be closed.
The issue with the key/iv was solved by adding them in the .py script as a string ('0123456789abcdef0123456789abcdef') then using  
key = key.decode('hex');
iv = iv.decode('hex');

**Comment by dangpzanco** [comment]
It seems you don't have a required library installed.

try Google.

...

...

...

And this:

[http://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher](url)

**Comment by progranadegrinder** [comment]
Okay, I'm getting the errors now, I cannot check if it's what you have because the post has been edited. But I cannot get past 0x8140000 due to the 2 files it calls for with the name not being there.

**Comment by SteveMyers75** [comment]
Sorry, I closed this issue and didn't see your response until today.
You will need to create those two files manually using a decrypted copy of you FW.IMG and a hex editor like HXD.

Using a clean FW.BIn file:
0x8140000.bin is 0xb4c88 to 0xb70ff 
0x5100000.bin is 0x1d5ac to 0x9fc87
(not sure why the error for the 2nd one says 0x5000000.bin is missing, it's actually 0x0x5100000.bin)

**Comment by SteveMyers75** [comment]
Sorry, I closed this issue and didn't see your response until today.
You will need to create those two files manually using a decrypted copy of 5.5.1 FW.IMG and a hex editor like HXD to copy the chuncks of data between these offsets:

Using a clean **decrypted** 5.5.1 FW.BIn file:
**0x8140000.bin** is 0xb4c88 to 0xb70ff (Including 0xb70ff)
**0x5100000.bin** is 0x89f1c to 0x9fc87 (Including 0x9fc87)

Not sure why the error for the 2nd one says 0x5000000.bin is missing. 
It's actually 0x5100000.bin it does not create for you.

Put those two in **\iosuhax\sections** and you should be good-to-go.

We are all hoping SMEA will "drop a bone to us dogs" on how he was able to use this tool.
(Not how it works, but how to use what it creates)

Right now, the Wii-U's status is stuck on "**_For Pirating Only!_**"
No CFW, no safe reNAND to play with :( 
It's a dead console anyways, would be nice to do something useful with it...
